# Generated by Django 4.1.7 on 2023-03-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0002_alter_service_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="price",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
