# Generated by Django 4.1.7 on 2023-03-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bands", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="band",
            name="image",
            field=models.URLField(default=""),
        ),
    ]
