# Generated by Django 4.1.7 on 2023-03-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bands", "0002_band_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="band",
            name="description",
            field=models.CharField(default="", max_length=500),
        ),
    ]
